# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-20 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestInfo',
            new_name='TestAdminInfo',
        ),
        migrations.AlterModelTable(
            name='testadmininfo',
            table='TestAdminInfo',
        ),
    ]
