# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-16 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_auto_20180716_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别'),
        ),
    ]
