# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-18 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='权重'),
        ),
    ]
