# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-19 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_slider', '0002_courseinfo_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='level',
            field=models.IntegerField(choices=[(1, '初级'), (2, '中级'), (3, '高级'), (4, '骨灰级')], default=1, verbose_name='课程等级'),
        ),
    ]
