# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-19 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_slider', '0003_auto_20180619_0214'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course2direct',
            unique_together=set([('course', 'direct')]),
        ),
    ]
