# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-19 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_slider', '0004_auto_20180619_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course2Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_slider.CourseInfo', verbose_name='课程')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_slider.CourseType', verbose_name='课程类型')),
            ],
            options={
                'verbose_name_plural': '课程与课程类型关系表',
                'db_table': 'Course2Type',
            },
        ),
        migrations.AlterUniqueTogether(
            name='course2type',
            unique_together=set([('course', 'type')]),
        ),
    ]
