# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-28 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article2Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '文章和标签关系表',
                'db_table': 'Article2Tag',
            },
        ),
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('detail', models.TextField(verbose_name='文章内容')),
                ('index_kind', models.IntegerField(choices=[(1, '技术'), (2, '新闻')], verbose_name='总分类')),
            ],
            options={
                'verbose_name_plural': '文章表',
                'db_table': 'ArticleInfo',
            },
        ),
        migrations.CreateModel(
            name='BillInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='详细内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.IntegerField(choices=[(-1, '未处理'), (0, '待处理'), (1, '已处理')], default=-1, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '保障单表',
                'db_table': 'BillInfo',
            },
        ),
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surfix', models.CharField(max_length=10, verbose_name='后缀')),
                ('signature', models.CharField(max_length=30, verbose_name='个性签名')),
                ('title', models.CharField(max_length=10, verbose_name='博客标题')),
            ],
            options={
                'verbose_name_plural': '个人博客表',
                'db_table': 'BlogInfo',
            },
        ),
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('detail', models.TextField(verbose_name='内容')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responsitory.ArticleInfo', verbose_name='文章')),
                ('comment_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responsitory.CommentInfo', verbose_name='父级评论')),
            ],
            options={
                'verbose_name_plural': '评论表',
                'db_table': 'CommentInfo',
            },
        ),
        migrations.CreateModel(
            name='EvaluateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(-1, '踩'), (1, '赞')], verbose_name='动作')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsitory.ArticleInfo', verbose_name='文章')),
            ],
            options={
                'verbose_name_plural': '赞踩表',
                'db_table': 'EvaluateInfo',
            },
        ),
        migrations.CreateModel(
            name='KindInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsitory.BlogInfo', verbose_name='所属博客')),
            ],
            options={
                'verbose_name_plural': '分类表',
                'db_table': 'KindInfo',
            },
        ),
        migrations.CreateModel(
            name='Star2Fans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '互粉表',
                'db_table': 'Star2Fans',
            },
        ),
        migrations.CreateModel(
            name='TagInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsitory.BlogInfo', verbose_name='所属博客')),
            ],
            options={
                'verbose_name_plural': '标签表',
                'db_table': 'TagInfo',
            },
        ),
        migrations.CreateModel(
            name='UsrInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('email', models.CharField(max_length=40, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('img', models.ImageField(upload_to='head', verbose_name='头像')),
                ('introduction', models.CharField(max_length=250, verbose_name='个人简介')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': 'UsrInfo',
            },
        ),
        migrations.AddField(
            model_name='star2fans',
            name='fans_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fans', to='responsitory.UsrInfo', verbose_name='粉丝用户'),
        ),
        migrations.AddField(
            model_name='star2fans',
            name='star_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Starts', to='responsitory.UsrInfo', verbose_name='明星用户'),
        ),
        migrations.AddField(
            model_name='evaluateinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsitory.UsrInfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsitory.UsrInfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsitory.UsrInfo', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='billinfo',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Handles', to='responsitory.UsrInfo', verbose_name='处理者'),
        ),
        migrations.AddField(
            model_name='billinfo',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Submits', to='responsitory.UsrInfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsitory.BlogInfo', verbose_name='所属博客'),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responsitory.KindInfo', verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='article2tag',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsitory.ArticleInfo', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='article2tag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsitory.TagInfo', verbose_name='标签'),
        ),
        migrations.AlterUniqueTogether(
            name='taginfo',
            unique_together=set([('blog', 'title')]),
        ),
        migrations.AlterUniqueTogether(
            name='evaluateinfo',
            unique_together=set([('article', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='article2tag',
            unique_together=set([('blog', 'tag')]),
        ),
    ]
