# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-28 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsitory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='index_kind',
            field=models.IntegerField(choices=[(1, '技术'), (2, '新闻')], default=2, verbose_name='总分类'),
        ),
    ]
