# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-28 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsitory', '0002_auto_20180628_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='img',
            field=models.ImageField(blank='True', null=True, upload_to='uploads/Article_head', verbose_name='文章图片'),
        ),
    ]
