# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-30 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsitory', '0004_auto_20180629_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinfo',
            name='solution',
            field=models.TextField(null=True, verbose_name='解决方案'),
        ),
        migrations.AlterField(
            model_name='usrinfo',
            name='introduction',
            field=models.CharField(max_length=250, null=True, verbose_name='个人简介'),
        ),
    ]
