# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-02 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsitory', '0005_auto_20180630_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrinfo',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='用户名'),
        ),
    ]
