# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-02 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsitory', '0006_auto_20180702_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='summary',
            field=models.TextField(null=True, verbose_name='简介'),
        ),
    ]
