# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-02 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsitory', '0007_articleinfo_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrinfo',
            name='img',
            field=models.ImageField(null=True, upload_to='head', verbose_name='头像'),
        ),
    ]
