# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-04 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsitory', '0011_auto_20180704_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article2tag',
            old_name='blog',
            new_name='article',
        ),
        migrations.AlterUniqueTogether(
            name='article2tag',
            unique_together=set([('article', 'tag')]),
        ),
    ]
