# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-06 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsitory', '0013_auto_20180706_1951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillInfo',
            new_name='TroubleInfo',
        ),
    ]
