# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-08 12:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='菜单名')),
                ('url_type', models.SmallIntegerField(choices=[(0, '固定url'), (1, '动态url')], verbose_name='URL类型')),
                ('url_name', models.CharField(max_length=128, verbose_name='URL后缀')),
            ],
            options={
                'verbose_name_plural': '菜单表',
                'db_table': 'MenuInfo',
            },
        ),
        migrations.CreateModel(
            name='RoleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='角色名')),
                ('menu', models.ManyToManyField(blank=True, null=True, to='canku.MenuInfo', verbose_name='菜单')),
            ],
            options={
                'verbose_name_plural': '角色表',
                'db_table': 'RoleInfo',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='head', verbose_name='头像')),
                ('identity_id', models.CharField(max_length=18, unique=True, verbose_name='身份证号码')),
                ('role', models.ManyToManyField(to='canku.RoleInfo', verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_customer_list', '查看客户列表@@@@@'), ('view_customer_info', '查看客户详情!!!!!!!'), ('edit_own_customer_info', '修改客户信息!!!!!!!!!')),
            },
        ),
    ]
