# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-08 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canku', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roleinfo',
            options={'permissions': (('crm_table_list', '可以查看@@@@@@@@@@@每张表里所有的数据'), ('crm_table_list_view', '可以访!!!!!!!!!!表里每条数据的修改页'), ('crm_table_list_change', '可以对XXXXXXXn表里的每条数据进行修改'), ('crm_table_obj_add_view', '可以访问kAAAAAadmin每张表的数据增加页'), ('crm_table_obj_add', '可以对kingadmin每张表进行数据添加'), ('crm_table_obj_add1', 'QWDAkingadmin每张表进行数据添加'))},
        ),
        migrations.AlterModelTable(
            name='roleinfo',
            table=None,
        ),
    ]
